{
 "title": "PayPulse Business Overview",
 "tags": [ "paypulse" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Payment TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(paypulse_payments_total[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Fraud alerts rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(paypulse_fraud_alerts_total[5m])) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Saga duration p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(paypulse_saga_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}